package qt.domain;
// Generated 2017-5-9 21:00:25 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Device generated by hbm2java
 */
@Entity
@Table(name="device")
public class Device  implements java.io.Serializable {


     private Integer id;
     private String mac;
     private String deviceKey;
     private Integer idType;
     private Integer status;
     private Date creationDate;
     private Date lastUpdateDate;
     private String creationIp;
     private String lastIp;

    public Device() {
    }

	
    public Device(Integer id, String deviceKey) {
        this.id = id;
        this.deviceKey = deviceKey;
    }
    public Device(Integer id, String mac, String deviceKey, Integer idType, Integer status, Date creationDate, Date lastUpdateDate, String creationIp, String lastIp) {
       this.id = id;
       this.mac = mac;
       this.deviceKey = deviceKey;
       this.idType = idType;
       this.status = status;
       this.creationDate = creationDate;
       this.lastUpdateDate = lastUpdateDate;
       this.creationIp = creationIp;
       this.lastIp = lastIp;
    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="mac", length=45)
    public String getMac() {
        return this.mac;
    }
    
    public void setMac(String mac) {
        this.mac = mac;
    }
    
    @Column(name="device_key", nullable=false, length=45)
    public String getDeviceKey() {
        return this.deviceKey;
    }
    
    public void setDeviceKey(String deviceKey) {
        this.deviceKey = deviceKey;
    }
    
    @Column(name="id_type")
    public Integer getIdType() {
        return this.idType;
    }
    
    public void setIdType(Integer idType) {
        this.idType = idType;
    }
    
    @Column(name="status")
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="creation_date", length=19)
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="last_update_date", length=19)
    public Date getLastUpdateDate() {
        return this.lastUpdateDate;
    }
    
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }
    
    @Column(name="creation_ip", length=16)
    public String getCreationIp() {
        return this.creationIp;
    }
    
    public void setCreationIp(String creationIp) {
        this.creationIp = creationIp;
    }
    
    @Column(name="last_ip", length=16)
    public String getLastIp() {
        return this.lastIp;
    }
    
    public void setLastIp(String lastIp) {
        this.lastIp = lastIp;
    }




}


