package qt.domain;
// Generated 2017-5-9 21:00:25 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name="user")
public class User  implements java.io.Serializable {


     private Integer id;
     private String username;
     private String password;
     private String name;
     private String hp;
     private String email;
     private String address;
     private String pic;
     private Integer status;
     private String token;
     private Date dueDate;
     private Date creationDate;
     private Date lastUpdateDate;
     private String creationIp;
     private String lastIp;
     private Date lastLoginDate;

    public User() {
    }

	
    public User(String username) {
        this.username = username;
    }
    public User(String username, String password, String name, String hp, String email, String address, String pic, Integer status, String token, Date dueDate, Date creationDate, Date lastUpdateDate, String creationIp, String lastIp) {
       this.username = username;
       this.password = password;
       this.name = name;
       this.hp = hp;
       this.email = email;
       this.address = address;
       this.pic = pic;
       this.status = status;
       this.token = token;
       this.dueDate = dueDate;
       this.creationDate = creationDate;
       this.lastUpdateDate = lastUpdateDate;
       this.creationIp = creationIp;
       this.lastIp = lastIp;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="username", nullable=false, length=30)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    
    @Column(name="password", length=64)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    
    @Column(name="name", length=30)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="hp", length=30)
    public String getHp() {
        return this.hp;
    }
    
    public void setHp(String hp) {
        this.hp = hp;
    }
    
    @Column(name="email", length=64)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    
    @Column(name="address", length=254)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    
    @Column(name="pic", length=254)
    public String getPic() {
        return this.pic;
    }
    
    public void setPic(String pic) {
        this.pic = pic;
    }
    
    @Column(name="status")
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    
    @Column(name="token", length=64)
    public String getToken() {
        return this.token;
    }
    
    public void setToken(String token) {
        this.token = token;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="due_date", length=19)
    public Date getDueDate() {
        return this.dueDate;
    }
    
    public void setDueDate(Date dueDate) {
        this.dueDate = dueDate;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="creation_date", length=19)
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="last_update_date", length=19)
    public Date getLastUpdateDate() {
        return this.lastUpdateDate;
    }
    
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }
    
    @Column(name="creation_ip", length=16)
    public String getCreationIp() {
        return this.creationIp;
    }
    
    public void setCreationIp(String creationIp) {
        this.creationIp = creationIp;
    }
    
    @Column(name="last_ip", length=16)
    public String getLastIp() {
        return this.lastIp;
    }
    
    public void setLastIp(String lastIp) {
        this.lastIp = lastIp;
    }


    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="last_login_date", length=19)
	public Date getLastLoginDate() {
		return lastLoginDate;
	}


	public void setLastLoginDate(Date lastLoginDate) {
		this.lastLoginDate = lastLoginDate;
	}




}


